FROM tensorflow/tensorflow:latest-gpu

RUN pip install Pillow==6.1.0
RUN pip install scikit-image==0.15.0
RUN pip install scikit-learn==0.21.2
RUN pip install scipy==1.1.0
RUN pip install pydot
RUN apt-get update
RUN apt-get install graphviz -y
RUN add-apt-repository ppa:git-core/ppa
RUN apt update
RUN apt-get install git -y


#### Add non-root user
ARG USERNAME=kasper
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s /bin/bash \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
    
# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
